name: Link Checker

on:
  pull_request:
    paths:
      - "**.md"
      - "**.mdx"
      - "docs/**"
  push:
    branches: [main]
    paths:
      - "**.md"
      - "**.mdx"
      - "docs/**"

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress --exclude-path 'node_modules' --exclude-path '.github/vscode-extension/vscode/node_modules' --exclude-path 'docs/verification' --exclude-path '.pytest_cache' './**/*.md' './docs/**/*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
